### PR TITLE
Update StateMachine.cs

### PR DESCRIPTION
**Pull request by sv955**
Fixed the issue causing state machine to go back to Default.Enter after the Default.Exit is called.

### CODE REVIEW

**Comment by swalex** [comment]
Hi Shobhit,

thank you for your merge request.

The transition of a state machine from the `Default.Exit` to the `Default.Enter` state is by design - this way it is possible to re-use a (nested) state machine during the next loop of an outer state machine.

Otherwise a state machine would remain locked in the exit state forever after it has worked through its states once.

What is the issue you are addressing with this fix? Maybe it can be resolved using a different setup of states?

**Comment by sv955** [comment]
Hey,

Thanks @swalex for your reply. 

Going back from Exit causing the state machine to run again for all the states.

Below is a sample of what I'm trying to implement :
Once the 'loadScene' in 'Enter' state is triggered, a new scene is loaded successfully and 'a' will be set to 1. That will move execution to 'Exit' state. 
Now, the transition coming back to 'Enter' state and tries to load the scene again. 
I can use the 'when' condition to stop the automatic transition from 'Enter' state but ideally transition should not occur from 'Exit' state to 'Enter' state.

Sample of the requirement:

public class Temp : MonoBehaviour
{
    StateMachine stateMachine = new StateMachine();

    void Start()
    {
        int a = 0;
        var loadScene= new ActionState
        {
            Enter = () =>
            {
                //load some scene and set a to 1 once scene is loaded.
                a = 1;

            },
            Exit = () => Debug.Log("Scene is loaded and state is exited"),
            Completed = () => a == 1
        };

        stateMachine.AddTransition(DefaultState.Enter, loadScene);
        stateMachine.AddTransition(loadScene,DefaultState.Exit);
    }

    // Update is called once per frame
    void Update()
    {
        stateMachine.Update(Time.deltaTime);
    }
}

**Comment by swalex** [comment]
The transition from the `Exit` back to the `Enter` state is by design and resembles the behavior of the animator state machine in Unity 3D.

The easiest resolution for the example you have posted would be to disable the `Temp` `MonoBehaviour` during a transition to the `Exit` state using something like `this.enabled = false;`:

```
...
stateMachine.AddTransition( DefaultState.Enter, loadScene );
stateMachine.AddTransition( loadScene, DefaultState.Exit ).OnTransition( () => enabled = false );
...
```
This would simply stop the `Temp` component from updating the state machine after the transition to the `Exit` state and prevent the engine from wasting the cycles on a state machine that does not need any updates anymore.

Another solution would be a transition to a custom "eternity" state after the `loadScene` state, which would keep the state machine locked in this state until the end of the liefetime of the `Temp` component. All you have to do is to create a new class implementing the `IState` interface and let the getter of the `Completed` property always return `false`:

```
...
stateMachine.AddTransition( DefaultState.Enter, loadScene );
stateMachine.AddTransition( loadScene, Eternity.State );
...

internal sealed class Eternity : IState
{
    private Eternity()
    {
    }

    internal static IState State { get; } = new Eternity();

    public bool Completed { get; } = false;

    public void Enter()
    {
    }

    public void Exit()
    {
    }

    public void Update( float _ )
    {
    }
}
```

The change requested here would break any existing state machines, because they expect to be executed repeatedly after each completion.

**Comment by sv955** [comment]
I get it now. Thanks @swalex for taking your time and sharing this valuable information. I really appreciate it.

**Pull request closed without merging**
